spring:
  datasource:
    # Onde esta destacado NOME_DO_BANCO e onde voce devera substituir pelo nome do seu banco de dados
    url: #jdbc:postgresql://localhost:5432/NOME_DO_BANCO: parte de conexao com o bd, e o restante e referentes a possiveis erro de timezone. Nao preciso decorar essa parte, so repetir para todos projetos
    username: #username do sue bd
    password: #senha do seu bd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true # O hibernate vai mostrar no terminal as tabelas na estrutura sql
  tasks:
    scheduling:
      cron: 0 0 8 ? * MON-FRI
  mail:
    host: smtp.gmail.com
    port: 587
    username: #seu email
    password: # sua senha criptografada (de preferencia)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    test-connection: false


logging:
  level:
    org:
      hibernate:
        type: trace
